apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  labels:
    app: broker
  name: broker
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: broker
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: broker
    spec:
      containers:
      - image: confluentinc/cp-zookeeper:latest
        name: "zookeeper-container"
        env:
        - name: "ZOOKEEPER_CLIENT_PORT"
          value: "2181"
        - name: "ZOOKEEPER_TICK_TIME"
          value: "2000"          
        imagePullPolicy: IfNotPresent
        resources:
          limits: 
            cpu: 250m
            memory: 250M
      - image: confluentinc/cp-kafka:latest
        ports:
          - containerPort: 29092
          - containerPort: 9092
        env:
          - name: CONFLUENT_SUPPORT_CUSTOMER_ID
            value: "anonymous"
          - name: KAFKA_ADVERTISED_LISTENERS
            value: "INTERNAL://broker:29092,LISTENER_EXTERNAL://localhost:9092"
          - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
            value: "true"
          - name: KAFKA_BROKER_ID
            value: "1"
          - name: KAFKA_DEFAULT_REPLICATION_FACTOR
            value: "1"
          - name: KAFKA_INTER_BROKER_LISTENER_NAME
            value: "INTERNAL"
          - name: KAFKA_LISTENERS
            value: "INTERNAL://:29092,LISTENER_EXTERNAL://:9092"
          - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
            value: "INTERNAL:PLAINTEXT,LISTENER_EXTERNAL:PLAINTEXT"
          - name: KAFKA_NUM_PARTITIONS
            value: "1"
          - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
            value: "1"
          - name: KAFKA_LOG_CLEANUP_POLICY
            value: "compact"
          - name: KAFKA_ZOOKEEPER_CONNECT
            value: "zookeeper:2181"
        imagePullPolicy: IfNotPresent
        name: "kafka-container"
        resources:
          limits: 
            cpu: 250m
            memory: 5G       
      restartPolicy: Always
    
---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: zookeeper
  name: zookeeper
spec:
  ports:
  - name: 2181-2181
    port: 2181
    protocol: TCP
    targetPort: 2181
  selector:
    app: broker

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: broker
  name: broker
spec:
  ports:
  - name: internal
    port: 29092
    targetPort: 29092 
  - name: external
    port: 9092
    protocol: TCP
    targetPort: 9092
  selector:
    app: broker