FROM ghcr.io/graalvm/native-image:ol8-java17

WORKDIR /builder
COPY . /builder/
ENV PATTERN='PATTERN="%d %p ${PID} --- [%t] %logger : %m%n"'
RUN  ./mvnw spring-boot:process-aot && ./mvnw native:build 
ENTRYPOINT [ "/builder/target/producer" ]